name: Exercise CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  Exercise-CI:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        
      - name: Setup Node 20 environment
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Build
        run: yarn build
        
      - name: Unit tests
        run: yarn test
        
      - name: Integration tests
        run: yarn test:e2e

      - name: JUnit Report Action
        if: always() 
        uses: mikepenz/action-junit-report@v5.2.0
        with:
          report_paths: "reports/*xml"
